# Generated by Django 3.0.2 on 2021-02-11 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='email')),
                ('username', models.CharField(max_length=40, unique=True, verbose_name='логин')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='дата регистрации')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='был в сети')),
                ('is_active', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_organizer', models.BooleanField(default=False)),
                ('is_owner', models.BooleanField(default=False)),
                ('sex', models.CharField(max_length=10, verbose_name='пол')),
                ('photo', models.ImageField(blank=True, default='default/profile_pic.jpg', upload_to='photos/%Y/%m/%d', verbose_name='фото')),
                ('vk_url', models.URLField(blank=True)),
                ('about', models.TextField(blank=True)),
                ('send_mail', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'пользователь',
                'verbose_name_plural': 'пользователи',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='название')),
                ('slug', models.SlugField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'город',
                'verbose_name_plural': 'города',
                'ordering': ['name'],
            },
        ),
    ]
