# Generated by Django 3.0.2 on 2021-02-11 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'событие-родитель', 'verbose_name_plural': 'события-родители'},
        ),
        migrations.AlterModelOptions(
            name='place',
            options={'verbose_name': 'место-родитель', 'verbose_name_plural': 'места-родители'},
        ),
        migrations.AlterField(
            model_name='place',
            name='short_description',
            field=models.CharField(blank=True, max_length=70),
        ),
    ]
