# Generated by Django 3.0.2 on 2021-02-12 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20210212_0207'),
    ]

    operations = [
        migrations.AddField(
            model_name='nontypeplace',
            name='work_time',
            field=models.CharField(default='не предоставлено', max_length=30),
        ),
    ]
