# Generated by Django 3.0.2 on 2021-02-12 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20210212_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='dislikes',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='likes',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
